---
- name: enable bluetooth
  ansible.builtin.systemd:
    name: bluetooth.service
    enabled: yes
    state: restarted

- name: restart pipewire-pulse as user
  ansible.builtin.systemd:
    name: pipewire-pulse.service
    scope: user
    state: restarted
    enabled: yes
  become: yes
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"

- name: enable polkit
  ansible.builtin.systemd:
    name: polkit
    scope: user
    enabled: yes
    state: started
  become: yes
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
