
- name: install packages for Sway
  pacman:
    name:
      - brightnessctl
      - gdm
      - jq
      - mako
      - sway
      - swayidle
      - swaylock
      - tilix  # Consider removing in favor of alacritty
      - waybar
      - wl-clipboard
      - xorg-server-xwayland
      - wmctrl
      - wf-recorder
  notify:
    - enable gdm

- name: install packages for desktop environment
  pacman:
    name:
      - polkit-gnome

- name: install packages for Wayland from AUR
  aur:
    name:
      - grimshot
      - redshift-wayland-git
      - wev
      - wshowkeys
      - wdisplays
  become: yes
  become_user: "{{ user.name }}"

- name: enable redshift service
  command: systemctl --user enable redshift.service
  become: yes
  become_user: "{{ user.name }}"
