---
- name: install GnuPG
  pacman:
    name:
      - ccid
      - gnupg
      - pcsclite
      - yubikey-manager-qt

- name: reload systemd config
  ansible.builtin.systemd:
    daemon_reload: yes

- name: enable pcscd
  ansible.builtin.systemd:
    name: pcscd.service
    enabled: yes
    state: started