---
- name: install CUPS printing system
  pacman:
    name:
      - cups
      - cups-pdf
      - ghostscript
      - gutenprint
      - gsfonts
      - hplip

- name: add user to lp group
  user:
    name: "{{ user.name }}"
    groups: lp
    append: yes

- name: enable CUPS
  service:
    name: org.cups.cupsd.service
    enabled: yes
    state: started
