---
- name: install bluetooth packages
  tags:
    - bluetooth
  pacman:
    name:
      - blueman
      - bluez
      - bluez-libs
      - bluez-utils
      - pulseaudio-bluetooth
  notify:
    - enable bluetooth
    - restart pulseaudio as user

- name: install polkit policy for blueman
  tags:
    - bluetooth
  copy:
    src: polkit-blueman.rules
    dest: /usr/share/polkit-1/rules.d/90-blueman.rules

