---
- name: configure systemd logind
  copy:
    src: logind.conf
    dest: /etc/systemd/logind.conf

- name: install Gnome
  pacman:
    name:
      - gnome
      - gnome-extra
      - gnome-tweaks
      - gendesk

- import_tasks: wayland.yml
- import_tasks: themes.yml
- import_tasks: media.yml

- name: install extra packages from repo
  pacman:
    name: "{{ extra_packages }}"

- name: install extra packages from AUR
  aur:
    name: "{{ extra_aur_packages }}"
  become: yes
  become_user: "{{ user.name }}"

- name: install host-specific packages from repo
  pacman:
    name: "{{ host_extra_packages }}"
  when: host_extra_packages | length > 0

- name: install host-specific packages from AUR
  aur:
    name: "{{ host_extra_aur_packages }}"
  become: yes
  become_user: "{{ user.name }}"
  when: host_extra_aur_packages is defined and host_extra_aur_packages|length > 0

- name: fix GoldenDict desktop file to work under Wayland
  lineinfile:
    path: /usr/share/applications/goldendict.desktop
    regexp: "^Exec=goldendict"
    line: "Exec=env QT_QPA_PLATFORM=xcb goldendict"
