---

- name: install GNOME extras
  pacman:
    name:
      - gnome-extra
      - gnome-shell-extensions

- name: install Gnome extensions
  kewlfft.aur.aur:
    name:
      - chrome-gnome-shell
      - gnome-shell-extension-gtktitlebar-git
      - gnome-shell-extension-system-monitor-git
  become: yes
  become_user: "{{ user.name }}"

- name: copy system-monitor.conf to temp
  copy:
    src: system-monitor.conf
    dest: "/var/tmp/system-monitor.conf"
    mode: 0644

- name: configure system-monitor extension  # noqa no-changed-when
  shell: "dconf load /org/gnome/shell/extensions/system-monitor/ < /var/tmp/system-monitor.conf"
  become: yes
  become_user: "{{ user.name }}"

# NOTE: psutil is not installed as ansible dependency for some reason and has to be installed manually.
# TODO: is this still required?
- name: install psutil for ansible
  pacman:
    name: python-psutil

- name: configure dconf
  become: no
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value | string }}"
  with_dict: "{{ dconf }}"

- import_tasks: bluetooth.yaml
- import_tasks: themes.yaml
- import_tasks: media.yaml
- import_tasks: wayland.yaml
