---
- name: configure systemd logind
  copy:
    src: logind.conf
    dest: /etc/systemd/logind.conf

- name: install Gnome
  pacman:
    name:
      - gnome
      - gnome-extra
      - gnome-tweaks
      - gendesk
  notify:
    - enable gdm

- name: create DConf config dir
  file:
    path: /etc/dconf/db/database.d
    state: directory

- name: configure DConf
  copy:
    src: dconf.conf
    dest: /etc/dconf/db/database.d/ruslan.conf
  notify: update dconf database

- name: install GNOME Shell Extensions support
  pacman:
    name:
      - gnome-shell-extensions
      - chrome-gnome-shell

- import_tasks: wayland.yml
- import_tasks: bluetooth.yml
- import_tasks: themes.yml
- import_tasks: media.yml

# TODO: verify if still needed.
#- name: fix GoldenDict desktop file to work under Wayland
#  lineinfile:
#    path: /usr/share/applications/goldendict.desktop
#    regexp: "^Exec=goldendict"
#    line: "Exec=env QT_QPA_PLATFORM=xcb goldendict"
