---
- name: install udiskie for automount
  pacman:
    name: udiskie

- name: install Intel Video Acceleration API driver
  pacman:
    name:
      - intel-media-driver

- name: install media codecs
  pacman:
    name:
      - flac
      - lame
      - opus
      - gstreamer
      - gst-libav
      - gstreamer-vaapi
      - gst-plugins-good
      - gst-plugins-ugly
      - gst-plugins-bad

- name: install pulseaudio
  pacman:
    name:
      - alsa-utils
      - pulseaudio
      - pulseaudio-alsa
      - pulseaudio-jack
      - pavucontrol
      - pamixer
      - paprefs
  notify:
    - restart pulseaudio as user

- name: install pro-audio packages
  pacman:
    name:
      - pro-audio
      - jack2

- name: add user to realtime group
  user:
    name: '{{ user.name }}'
    groups: realtime
    append: yes
  notify:
    - restart pulseaudio as user
