---
- name: install media codecs
  pacman:
    name:
      - flac
      - lame
      - opus
      - gstreamer
      - gst-libav
      - gstreamer-vaapi
      - gst-plugins-good
      - gst-plugins-ugly
      - gst-plugins-bad

- name: install pulseaudio
  pacman:
    name:
      - alsa-utils
      - pulseaudio
      - pulseaudio-alsa
      - pulseaudio-jack
      - pipewire
      - pipewire-docs
      - libpipewire02  # For Chrome screen sharing to work as long as they ship with v0.2
      - pavucontrol
      - pamixer
      - paprefs
  notify:
    - restart pulseaudio as user

- name: install packages for audio recording and editing
  pacman:
    name:
      - realtime-privileges
      - ardour
      - cadence
      - lv2-plugins

- name: add user to realtime group
  user:
    name: '{{ user.name }}'
    groups: realtime
    append: yes
  notify:
    - restart pulseaudio as user