---
- name: install GTK and Qt themes
  pacman:
    name:
      - breeze
      - breeze-gtk
      - breeze-icons
      - gnome-themes-extra
      - qt5
      - qt5-base
      - qt5-wayland
      - qt5ct

- name: install fonts
  pacman:
    name:
      - ttf-dejavu
      - ttf-joypixels
      # Fonts to use asian characters
      - ttf-arphic-uming
      - ttf-baekmuk
      - ttf-indic-otf
      # Emoji
      - noto-fonts
      - ttf-hannom  # vietnamese

- name: install fonts from AUR
  kewlfft.aur.aur:
    name:
      - nerd-fonts-iosevka
      - ttf-cmu-serif
  become: yes
  become_user: "{{ user.name }}"

- name: set Breeze Gnome theme
  become: no
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value | string }}"
  with_dict:
    "/org/gnome/desktop/interface/gtk-theme": "'Breeze'"
    "/org/gnome/desktop/interface/cursor-theme": "'Breeze_Snow'"
    "/org/gnome/desktop/interface/icon-theme": "'breeze'"
