---
- name: install fprintd
  pacman:
    name:
      - fprintd

- name: restrict fingerprint enroll via polkit
  copy:
    src: polkit/50-net.reactivated.fprint-enroll.rules
    dest: /usr/share/polkit-1/rules.d/50-net.reactivated.fprint-enroll.rules
