---
- name: install TLP power management
  pacman:
    name:
      - tlp
      - tlp-rdw
      - acpid
      - ethtool
      - smartmontools

- name: mask systemd radio service
  ansible.builtin.systemd:
    name: systemd-rfkill.service
    masked: yes

- name: mask systemd radio socket  # noqa no-changed-when
  ansible.builtin.systemd:
    name: systemd-rfkill.socket
    masked: yes

- name: enable TLP service
  ansible.builtin.systemd:
    name: tlp.service
    enabled: yes
    state: restarted

- name: enable NetworkManager-dispatcher service
  ansible.builtin.systemd:
    name: NetworkManager-dispatcher.service
    enabled: yes
    state: started
