#!/bin/sh

source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

# Set screen wallpaper (see man for choosing image).
feh --bg-fill ${HOME}/.xmonad/images/zoresvit_wallpaper.png

xset -b  # Turn off PC speaker bell.
xsetroot -cursor_name left_ptr  # Allow custom pointers.

# Start keyring for applications that expect access to system keyring.
gnome-keyring-daemon --daemonize --start \
    --components=gpg,pkcs11,secrets,ssh > /dev/null

setsid "${HOME}/.xmonad/lock.sh" &
udiskie > /dev/null 2>&1 &

stalonetray &  # Start system tray.

# Try to start Compton compositor on up to 4 displays.
seq 0 3 | xargs -l1 -I@ compton -b -d :0.@ > /dev/null 2>&1 &

gnome-screensaver > /dev/null 2>&1 &
unclutter -grab -jitter 5 &
