---
- name: install cron
  pacman:
    name: cronie
  notify:
    - enable cron

- name: enable cron
  systemd:
    name: cronie.service
    enabled: yes
    state: started

- name: install GnuPG
  pacman:
    name:
      - ccid
      - gnupg
      - pcsclite
      - yubikey-manager-qt
  notify:
    - enable pcscd

- name: enable pcscd
  systemd:
    name: pcscd.service
    enabled: yes
    state: started

- import_tasks: printing.yaml