---
- name: install cron
  pacman:
    name: cronie
  notify:
    - enable cron

- name: enable cron
  systemd:
    name: cronie.service
    enabled: yes
    state: started

- import_tasks: printing.yaml